const actionTypes: DocumentNS.IActionTypes = {
    DOCUMENTS_SET_INITIAL_DATA: 'DOCUMENTS_SET_INITIAL_DATA',
    DOCUMENTS_OPEN_ADD_MODAL: 'DOCUMENTS_OPEN_ADD_MODAL',
    DOCUMENTS_OPEN_DELETE_MODAL: 'DOCUMENTS_OPEN_DELETE_MODAL',
    DOCUMENTS_SET_SEARCH_DATA: 'DOCUMENTS_SET_SEARCH_DATA',
};

export default actionTypes;